version: "3.8"

services:
  db:
    container_name: nextauthv5_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: next_auth_v5
      POSTGRES_USER: nextauthv5
      POSTGRES_PASSWORD: nextauthv5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
